name: Daily job Scraper to Google Sheets + Telegram

Triggers:
- 📆 Daily at 9 AM UTC
- ▶️ Manually via GitHub UI

Secrets expected:
- GOOGLE_CREDENTIALS_JSON
- TELEGRAM_BOT_TOKEN
- TELEGRAM_CHAT_ID

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9am UTC
  workflow_dispatch:      # Manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python ebay_to_gsheets_telegram.py