# dbt/dbt_project.yml
name: 'patient_engagement_pipeline'
version: '1.0'
profile: 'default'
config-version: 2

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  patient_engagement_pipeline:
    +materialized: view