-- Create table to store transformed product data in Amazon Redshift
-- This table matches the schema of products_transformed.csv generated by the Airflow DAG

CREATE TABLE IF NOT EXISTS product_data (
    id              INTEGER     PRIMARY KEY,
    title           VARCHAR(256),
    price           DECIMAL(10,2),
    description     VARCHAR(1000),
    category        VARCHAR(100),
    image           VARCHAR(512),
    rating_rate     DECIMAL(5,2),
    rating_count    INTEGER,
    price_with_tax  DECIMAL(10,2),
    ingestion_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);