"""
📄 encounter_parser.py

This script extracts Encounter resources from FHIR Bundles generated by Synthea.

Author: Bita Ashoori
"""

import os
import json
import pandas as pd

INPUT_DIR = "../data/fhir"
OUTPUT_FILE = "../data/output/parsed_encounters.csv"
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

encounter_records = []

for filename in os.listdir(INPUT_DIR):
    if filename.endswith(".json"):
        with open(os.path.join(INPUT_DIR, filename), "r") as f:
            bundle = json.load(f)

        if bundle.get("resourceType") != "Bundle":
            continue

        for entry in bundle.get("entry", []):
            resource = entry.get("resource", {})
            if resource.get("resourceType") == "Encounter":
                encounter_id = resource.get("id", "")
                subject_ref = resource.get("subject", {}).get("reference", "")
                status = resource.get("status", "")
                encounter_type = resource.get("type", [{}])[0].get("text", "")
                period_start = resource.get("period", {}).get("start", "")
                period_end = resource.get("period", {}).get("end", "")

                encounter_records.append([
                    encounter_id, subject_ref, status, encounter_type,
                    period_start, period_end
                ])

columns = [
    "Encounter ID", "Subject Reference", "Status",
    "Type", "Start Time", "End Time"
]

df = pd.DataFrame(encounter_records, columns=columns)
df.to_csv(OUTPUT_FILE, index=False)
print(f"✅ Extracted {len(df)} encounters to: {OUTPUT_FILE}")
